services:
  mssql:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - abp-network

  seq:
    container_name: seq
    image: datalust/seq:2024.2
    ports:
      - 8889:80
      - 5341:5341
    networks:
      - abp-network
    environment:
      - ACCEPT_EULA=Y

volumes:
  sqldata:
networks:
  abp-network:
    driver: bridge
    external: true
